server:
  port: 8110 # Server port
spring:
  profiles:
    active: dev
  application:
    name: service-core # Service name
  # Data Source
  datasource:
    type: com.zaxxer.hikari.HikariDataSource
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/srb-core?serverTimezone=GMT%2B8&characterEncoding=utf-8
    username: root
    password: 598607184zhe
  # redis configuration
  redis:
    host: 192.168.56.101
    port: 6379
    database: 0
    timeout: 3000ms # The maximum waiting time
    lettuce:
      pool:
        max-active: 20 # The maximum connection
        max-wait: -1
        max-idle: 8
        min-idle: 0
  cloud:
    nacos:
      discovery:
        server-addr: 192.168.56.101:8848 # nacos Configuration Service address
  rabbitmq:
    host: 192.168.56.101
    port: 5672
    virtual-host: /srb-host
    username: srb-user
    password: 1234
mybatis-plus:
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
  mapper-locations: classpath:com/wwj/srb/core/mapper/xml/*.xml
