server:
  port: 8120 # server port
spring:
  profiles:
    active: dev
  application:
    name: service-sms # service name
  # redis configuration
  redis:
    host: 192.168.56.101
    port: 6379
    database: 0
    timeout: 3000ms # The maximum wait time
    lettuce:
      pool:
        max-active: 20 # The maximum number of connections. A negative value means there is no limit. The default value is 8
        max-wait: -1 # The maximum blocking time. A negative value means there is no limit. The default value is -1
        max-idle: 8 # The maximum number of idle connections is 8 by default
        min-idle: 0 # The minimum number of idle connections is 0 by default
  cloud:
    nacos:
      discovery:
        server-addr: 192.168.56.101:8848 # Configure nacos registry ip address
  rabbitmq:
    host: 192.168.56.101
    port: 5672
    virtual-host: /srb-host
    username: srb-user
    password: 1234

# The default timeout time of openfeign is 1 second. To prevent the remote call from timeout, the timeout time is set to be longer here
feign:
  client:
    config:
      default:
        connectTimeout: 10000 # Connection timeout configuration
        readTimeout: 60000 # Execute timeout configuration
  sentinel:
    enabled: true # Enable openfeign support for sentinel


# The service will keep the verification code into redis and we can get that code from redis server
# Ali cloud sms service configuration
aliyun:
  sms:
    region-id: xxxxxxxxxxxxx
    key-id: xxxxxxxxxxxxx
    key-secret: xxxxxxxxxxxxx
    template-code: xxxxxxxxxxxxx
    sign-name: 谷粒
logging:
  level:
    com.wwj.srb.sms.client.CoreUserInfoClient: DEBUG # Monitor the remote service interface at the debug level